[package]
name = "blockbuster"
description = "Metaplex canonical program parsers, for indexing, analytics etc...."
version = "0.2.0"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/blockbuster"
license = "AGPL-3.0"
edition = "2021"
readme = "../README.md"

[dependencies]
spl-account-compression = { version = "0.1.2", git = "https://github.com/danenbm/solana-program-library", branch = "danenbm/changelog_event", features = ["no-entrypoint"] }
spl-noop = { version = "0.1.2", features = ["no-entrypoint"] }
mpl-bubblegum = { version = "0.1.2", features = ["no-entrypoint"], git ="https://github.com/metaplex-foundation/metaplex-program-library", branch = "danenbm/update_bubblegum_events" }
mpl-candy-guard = { git = "https://github.com/metaplex-foundation/candy-guard", branch = "stranzhay/read-api", features = ["no-entrypoint"] }
mpl-candy-machine-core = { version = "0.0.3", git = "https://github.com/metaplex-foundation/metaplex-program-library", branch = "stranzhay/read-api", features = ["no-entrypoint"] }
mpl-token-metadata = { version = "1.4.1", git = "https://github.com/metaplex-foundation/metaplex-program-library", branch = "stranzhay/read-api", features = ["no-entrypoint", "serde-feature"] }
plerkle_serialization = { version = "0.4.7", git = "https://github.com/metaplex-foundation/digital-asset-validator-plugin"}
spl-token = { version = "3.0.1", features = ["no-entrypoint"] }
async-trait = "0.1.57"
lazy_static = "1.4.0"
flatbuffers = "2.1.2"
borsh = "0.9.3"
anchor-lang = "0.25.0"
thiserror = "1.0.32"
solana-sdk = "1.10.38"

[dev-dependencies]
rand = "0.8.5"
solana-geyser-plugin-interface = { version = ">=1.10" }
solana-sdk = ">=1.10"
spl-concurrent-merkle-tree = "0.1.1"


